src/components/Apps.vue
src/components/Panel.vue
src/components/TopBar.vue
src/router/index.js

Fixed the problem that the ESC key conflicts when using the vi editor in the terminal.
Change routing to hash mode.

🐞 fix: Terminal bug

---

package.json
src/assets/scss/app.scss
src/components/Settings.vue
src/components/SmartBlock.vue
src/components/SyncBlock.vue
src/components/SyncPanel.vue
yarn.lock

Fix Sync display error
Fix Sync Downoad url error
Fix Smart Block display error
Fix widgets settings dispaly error

🐞 fix: Fixed Sync Error

---

src/components/Apps/AppCard.vue
src/components/SyncBlock.vue
src/components/forms/IconInput.vue
src/components/forms/InputGroup.vue

Fixed some spelling problems
Fixed the bug of synchronization module
Fixed the problem of data display error when manually installing apps

🐞 fix: Fixed bugs

---

src/App.vue
src/components/Panel.vue
src/components/forms/InputGroup.vue

🐞 fix: Fixed display bugs.

---

src/components/Panel.vue
src/components/forms/ImportPanel.vue

Fixed an error when importing and exporting appfile.

🐞 fix: Fixed Import Error

---

src/assets/lang/de_de.js

Fix missing translated content

🐞 fix: Fixed  translation

---

src/App.vue
src/assets/lang/index.js
src/assets/lang/zh_cn.js
src/components/TopBar.vue
src/store/index.js
src/views/Login.vue

🎈 perf: Modify language

---

src/components/TopBar.vue

🐞 fix: Fixed language

---

src/App.vue
src/components/TopBar.vue
src/mixins/mixin.js
src/store/index.js
src/widgets/Disks.vue

Fixed the language initialization bug

🐞 fix: Fix language

---

src/components/BrandBar.vue

Removed unnecessary space in BrandBar.vue

---

package.json
yarn.lock

Deprecate node-sass, use sass instead

build(Update Dependencies):

---

src/components/CoreService.vue

在USB通知里增加打开files的方法
Add a method to open files in USB notifications

:bug: fix(Open file window by YouShouldKnow.)

---

src/assets/lang/en_US.json
src/components/Apps/AppCard.vue
src/events/message_bus.js
src/service/service.js

1. Cloud disk can be mounted in file manager. 
2. Apps in the app Store can be upgraded.

:bulb: dev-0.4.2-alpha

---

src/components/Storage/StorageManagerPanel.vue

Operation button are not displayed during the creating process

🐛 : Fix : Operation button are not displayed during the creating process.

---

src/components/noticBlock/noticeBlock.vue
src/components/smartHome/SmartBlock.vue
src/components/syncthing/SyncBlock.vue

Adjust the height of home page.

---

main/src/components/Apps/ComposeConfig.vue
main/src/components/forms/Ports.vue

 :bug: The type of the returned result for port validation is incorrect.

---

main/src/components/noticBlock/noticeBlock.vue
main/src/widgets/Network.vue

:sparkles: Add title.
:goal_net: Embrace errors to avoid undefined.

:sparkles: Add title.

---

main/src/main.js
main/src/router/index.js

1. move checkToken outside router beforeEach
2. change token source from hash to location.search

:triangular_flag_on_post:check url token

---

main/src/components/Apps/AppPanel.vue
main/src/components/fileList/CreatePanel.vue
main/src/components/fileList/FilePanel.vue

:sparkles: Introducing new features which can create file or folder.
:art: Improving structure / format of the code.

:sparkles: Introducing new features which can create file or folder.

---

main/src/components/Apps/ComposeConfig.vue

[🔀 Change input fields order](https://github.com/IceWhaleTech/CasaOS-UI/commit/93f5835eaf41e88b57afcb7bb76e07de71e3d3c6)

:bug: Fixing a bug that network is random.

---

main/src/components/Apps/AppCard.vue

to toast the app is the latest when checking the update.
known problem:
- the toast is only English. may It should be i18n

fix: to toast the app is the latest when checking the update

---

main/src/components/Apps/ComposeConfig.vue

fix: privilege may be null when sometime

---

main/src/components/Apps/ComposeConfig.vue
main/src/components/forms/InputGroup.vue

refactor input group from option api to composition api

refactor: input group as composition api

---

.yarnrc.yml

chore: revert yarnrc

---

main/src/components/AppStore/AppRecommend/AppRecommend.vue
main/src/components/AppStore/AppRecommend/index.js
main/src/components/AppStore/index.js
main/src/components/Apps/AppPanel.vue

https://github.com/IceWhaleTech/CasaOS-UI/pull/206

refactor: recommend app

---

main/src/components/forms/Ports.vue

https://github.com/IceWhaleTech/CasaOS-UI/pull/202

refactor: simply the code

---

main/package.json
yarn.lock

cherry-pick https://github.com/IceWhaleTech/CasaOS-UI/pull/198 for feature

chore: delete unused component

---

main/src/mixins/IconContainerMixin.js
main/src/mixins/mixin.js

fixed https://github.com/IceWhaleTech/CasaOS/issues/1057.

:sparkles:(files) show svg preview.

---

README.md

As a first-time contributor to this project, I was missing few steps in the README that would have allowed me to have a dev server up and running as fast as possible.
1. Add prerequisites information (node and yarn)
2. Add environment variables information to connect dev server with backend

docs: update development instructions
